# encoding: utf-8

require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end
require 'rake'

# some jeweler tasks (like building gem for release) croak on syck now it seems
begin
  require 'psych' if RUBY_VERSION =~ /^1\.9\./
rescue LoadError
  puts('WARNING: psych not available, defaulting yaml engine to old unmaintained syck')
end
begin
  require 'jeweler'
rescue LoadError
  puts 'WARNING: missing jeweler library, some tasks are not available'
else
  Jeweler::Tasks.new do |gem|
    # gem is a Gem::Specification... see http://docs.rubygems.org/read/chapter/20 for more options
    gem.name = "activerecord_has_changed"
    gem.homepage = "http://github.com/dburry/activerecord_has_changed"
    gem.license = "MIT"
    gem.summary = %Q{Shortcuts for checking what has changed in update handlers}
    gem.description = %Q{Shortcuts for checking what has changed in update handlers}
    gem.email = "dburry@jackal"
    gem.authors = ["David Burry"]
    # dependencies defined in Gemfile
  end
  Jeweler::RubygemsDotOrgTasks.new
end

begin
  require 'rake/testtask'
rescue LoadError
  puts 'WARNING: missing test library, some tasks are not available'
else
  task :default => :test
  Rake::TestTask.new(:test) do |test|
    test.libs << 'lib' << 'test'
    test.pattern = 'test/**/test_*.rb'
  end
end

if RUBY_VERSION =~ /^1\.8\./
  begin
    require 'rcov/rcovtask'
  rescue LoadError
    puts 'WARNING: missing rcov library, some tasks are not available'
  else
    Rcov::RcovTask.new do |test|
      test.libs << 'test'
      test.pattern = 'test/**/test_*.rb'
    end
  end
elsif RUBY_VERSION =~ /^1\.9\./
  begin
    require 'simplecov'
  rescue LoadError
    puts 'WARNING: missing simplecov library, some tasks are not available'
  else
    desc 'Analyze code coverage with tests'
    task :coverage => 'coverage:clobber' do
      ENV['USE_SIMPLECOV'] = :true.to_s
      Rake::Task['test'].invoke
      # see top of test helper for the rest of this task, which is triggered with the environment var....
    end
    namespace :coverage do
      desc 'Remove output directory generated by simplecov'
      task :clobber do
        FileUtils.rm_rf(File.expand_path('../coverage', __FILE__))
      end
    end
  end
end

if RUBY_VERSION =~ /^1\.9/
  begin
    require 'rdoc/task'
  rescue LoadError
    puts 'WARNING: missing rdoc library, some tasks are not available'
  else
    RDoc::Task.new do |rdoc|
      version = File.exist?('VERSION') ? File.read('VERSION') : ""
      rdoc.rdoc_dir = 'rdoc'
      rdoc.title = "http_session #{version}"
      rdoc.rdoc_files.include('README*')
      rdoc.rdoc_files.include('lib/**/*.rb')
    end
  end
end
